replicaCount: 1
image:
    repository: quay.io/minio/minio
    tag: latest
    pullPolicy: Always
service:
    port: 9090
    targetPort: 9090
    type: NodePort
    nodePort: 30090
hostPath: /home/felixchung/data