apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "minio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "minio.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: storage
              mountPath: /data
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              /certgen -host datamgmtdemo01.eastasia.cloudapp.azure.com
              mkdir /cert
              mv private.key /cert
              mv public.crt /cert
              minio server --certs-dir /cert /data --console-address :{{ .Values.service.consolePort }}
          ports:
            - containerPort: {{ .Values.service.consolePort }}
            - containerPort: {{ .Values.service.s3Port }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "minio.fullname" . }}-pvc